# Permalinks
permalink: /:categories/:year/:month/:day/:title.html

avatar: https://avatars.githubusercontent.com/hvanruys

# Setup
title:            EUMETCastView
tagline:          'An EUMETCAST Viewer'
description:      'A viewer for the EUMETCast transmissions.'
url:              http://hvanruys.github.io
#baseurl:          /

author:
  name:           'Hugo Van Ruyskensvelde'
  url:

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/hvanruys/EUMETCastView

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
